- name: "creating directory for system status"
  file:
    path: "{{ logs_dir }}/system"
    state: directory

- name: "Get logs for each host"
  become: yes
  shell: |-
          set -x
          systemd-cgls --full --all --no-pager > {{ logs_dir }}/system/systemd-cgls.txt
          ip addr > {{ logs_dir }}/system/ip-addr.txt
          ip route > {{ logs_dir }}/system/ip-route.txt
          lsblk > {{ logs_dir }}/system/lsblk.txt
          mount > {{ logs_dir }}/system/mount.txt
          docker images > {{ logs_dir }}/system/docker-images.txt
          ps aux --sort=-%mem > {{ logs_dir }}/system/ps.txt
  args:
    executable: /bin/bash
  ignore_errors: True

- name: "Downloads logs to executor"
  synchronize:
    src: "{{ logs_dir }}/system"
    dest: "{{ zuul.executor.log_root }}/{{ inventory_hostname }}"
    mode: pull
  ignore_errors: True
