apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  annotations:
    config.k8s.io/function: |
      container:
        image: quay.io/aodinokov/sops:v0.0.2
data:
  ignore-mac: true
  override-detached-annotations: |-
    config.kubernetes.io/index, config.kubernetes.io/path, config.k8s.io/id, kustomize.config.k8s.io/id
