---
- block:
  - name: Ensuring Libvirt, Qemu and support packages are present
    become: true
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
    yum:
      name:
        - libguestfs-tools
        - libvirt
        - libvirt-devel
        - libvirt-daemon-kvm
        - qemu-kvm
        - virt-install
      state: present
  - name: Ensuring Libvirt, Qemu and support packages are present
    become: true
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    apt:
      name:
        - qemu
        - libvirt-bin
        - libguestfs-tools
        - qemu-kvm
        - virtinst
        - python-lxml
        - python3-lxml
        - python3-libvirt
        - python-libvirt
        - dnsmasq
        - ebtables
      state: present
  - name: Add user "{{ ansible_user }}" to libvirt group
    become: true
    user:
      name: "{{ ansible_user }}"
      groups:
      - libvirt
      append: yes
  - name: Reset ssh connection to allow user changes to affect "{{ ansible_user }}"
    meta: reset_connection
    ignore_errors: true
  - name: Start libvirtd
    service:
      name: libvirtd
      state: started
      enabled: true
    become: true

