- name: reload systemd configuration
  become: yes
  systemd:
    daemon_reload: yes

- name: restart sushy-emulator
  become: yes
  service:
    name: sushy-tools
    state: restarted
    enabled: true