apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - baremetalhost.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: node02-network-data
    files:
      - networkData
  - name: node02-bmc-secret
    literals:
      - username=username
      - password=password
