apiVersion: airshipit.org/v1alpha1
kind: ReplacementTransformer
metadata:
  name: ephemeral-secret-replacement
  annotations:
    config.kubernetes.io/function: |
      container:
        image: quay.io/aodinokov/replacement-default:v0.0.2
replacements:
- source:
    multiref:
      refs:
      - objref:
          kind: Secret
          name: node1-bmc-secret
        fieldref: stringData.userData|runcmd[8]
      - objref:
          name: ephemeral-catalogue
        fieldref: versions.docker-ce
      template: |
        {{ regexReplaceAll "docker-ce . grep 19.03.12" (index .Values 0) (printf "docker-ce | grep %s" (index .Values 1)) }}
  target:
    objref:
      kind: Secret
      name: node1-bmc-secret
    fieldrefs: 
    - stringData.userData|runcmd[8]
- source:
    multiref:
      refs:
      - objref:
          kind: Secret
          name: node1-bmc-secret
        fieldref: stringData.userData|runcmd[8]
      - objref:
          name: ephemeral-catalogue
        fieldref: versions.docker-ce-cli
      template: |
        {{ regexReplaceAll "docker-ce-cli . grep 19.03.12" (index .Values 0) (printf "docker-ce-cli | grep %s" (index .Values 1)) }}
  target:
    objref:
      kind: Secret
      name: node1-bmc-secret
    fieldrefs:
    - stringData.userData|runcmd[8]
- source:
    multiref:
      refs:
      - objref:
          kind: Secret
          name: node1-bmc-secret
        fieldref: stringData.userData|runcmd[=apt install -y kubelet=1.18.6-00 kubeadm=1.18.6-00 kubectl=1.18.6-00]
      - objref:
          name: ephemeral-catalogue
        fieldref: versions.kubelet
      - objref:
          name: ephemeral-catalogue
        fieldref: versions.kubeadm
      - objref:
          name: ephemeral-catalogue
        fieldref: versions.kubectl
      template: |
        {{ regexReplaceAll "kubectl=1.18.6-00" (regexReplaceAll "kubeadm=1.18.6-00" (regexReplaceAll "kubelet=1.18.6-00" (index .Values 0) (printf "kubelet=%s" (index .Values 1))) (printf "kubelet=%s" (index .Values 2))) (printf "kubelet=%s" (index .Values 3)) }}
  target:
    objref:
      kind: Secret
      name: node1-bmc-secret
    fieldrefs:
    - stringData.userData|runcmd[=apt install -y kubelet=1.18.6-00 kubeadm=1.18.6-00 kubectl=1.18.6-00]
- source:
    objref:
      name: ephemeral-catalogue
    fieldref: creds.users
  target:
    objref:
      kind: Secret
      name: node1-bmc-secret
    fieldrefs:
    - stringData.userData|chpasswd.list
- source:
    objref:
      name: ephemeral-catalogue
    fieldref: creds.certificate-authority-data
  target:
    objref:
      kind: Secret
      name: node1-bmc-secret
    fieldrefs:
    - stringData.userData|write_files.[path=/etc/kubernetes/admin.conf].content | clusters.[name=kubernetes].cluster.certificate-authority-data
    - stringData.userData|write_files.[path=/etc/kubernetes/pki/ca.crt].content
- source:
    objref:
      name: ephemeral-catalogue
    fieldref: creds.certificate-authority-key-data
  target:
    objref:
      kind: Secret
      name: node1-bmc-secret
    fieldrefs:
    - stringData.userData|write_files.[path=/etc/kubernetes/pki/ca.key].content
- source:
    objref:
      name: ephemeral-catalogue
    fieldref: creds.client-certificate-data
  target:
    objref:
      kind: Secret
      name: node1-bmc-secret
    fieldrefs:
    - stringData.userData|write_files.[path=/etc/kubernetes/admin.conf].content | users.[name=kubernetes-admin].user.client-certificate-data
- source:
    objref:
      name: ephemeral-catalogue
    fieldref: creds.client-key-data
  target:
    objref:
      kind: Secret
      name: node1-bmc-secret
    fieldrefs:
    - stringData.userData|write_files.[path=/etc/kubernetes/admin.conf].content | users.[name=kubernetes-admin].user.client-key-data
