apiVersion: airshipit.org/v1alpha1
kind: Templater
metadata:
  name: m3-host-template
  annotations:
    config.kubernetes.io/function: |
      container:
        image: quay.io/aodinokov/templater-default:v0.0.1

# values:
  # hosts:
  #    (filled in from the comprehensive site-wide host-catalogue)
  # hostsToGenerate:
  #    (filled in with phase-specific host-generation-catalogue)
  # commonNetworking:
  #    (filled in with the type-specific common-networking-catalogue)

template: |
  {{- $envAll := . }}
  {{- range .hostsToGenerate }}
  {{- $hostName := . }}
  {{- $host := index $envAll.hosts $hostName }}
  ---
  apiVersion: metal3.io/v1alpha1
  kind: BareMetalHost
  metadata:
    annotations:
    labels:
    name: {{ $hostName }}
  spec:
    online: false
    bootMACAddress: {{ $host.macAddress }}
    networkData:
      name: {{ $hostName }}-network-data
      namespace: default
    bmc:
      address: {{ $host.bmcAddress }}
      credentialsName: {{ $hostName }}-bmc-secret
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: {{ $hostName }}-bmc-secret
  data:
    username: {{ $host.bmcUsername | b64enc }}
    password: {{ $host.bmcPassword | b64enc }}
  type: Opaque
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: {{ $hostName }}-network-data
  stringData:
    networkData: |
      links:
        {{- range $envAll.commonNetworking.links }}
      - {{ toYaml . | indent 6 | trim }}
        {{- if $host.macAddresses }}
        ethernet_mac_address: {{ index $host.macAddresses .id }}
        {{- end }}
        {{- end }}
      networks:
        {{- range $envAll.commonNetworking.networks }}
      - {{ toYaml . | indent 6 | trim }}
        ip_address: {{ index $host.ipAddresses .id }}
        {{- end }}
      services:
  {{ toYaml $envAll.commonNetworking.services | indent 6 }}
  type: Opaque

  {{ end -}}
