apiVersion: airshipit.org/v1alpha1
kind: NodeBootstrap
metadata:
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: /home/ubuntu/go/bin/config-function
spec:
  operations:
  - action: doRemoteDirect
  bmh:
    name: bmo-master-0
    namespace: bmo-project
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bmo-master-0
  namespace: bmo-project
spec:
  bmc:
    address: redfish://127.0.0.1:8443/redfish/v1/Systems/air-ephemeral
    credentialsName: bmo-master-0-bmc-secret
  bootMACAddress: 98:03:9b:61:80:48
  consumerRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: Machine
    name: bmo-master-0
    namespace: bmo-project
  externallyProvisioned: true
  hardwareProfile: default
  image:
    url: http://127.0.0.1:8100/debian-custom.iso
  online: true
  disableCertificateVerification: true
  rootDeviceHints:
    model: default
    vendor: default
---
apiVersion: v1
kind: Secret
metadata:
  name: bmo-master-0-bmc-secret
  namespace: bmo-project
type: Opaque
stringData:
  username: username
  password: password
